
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpjpdgfnkprowesdobkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwanBkZ2Zua3Byb3dlc2RvYmt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NjE2MTksImV4cCI6MjA2MTUzNzYxOX0.EuGRwHxRmVrSlHhOeUV3WQFuwzjta5ym_YCXDv5uH1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'implicit',
    debug: true, // Enable for better debugging
    cookieOptions: {
      name: 'hogflix_auth',
      lifetime: 60 * 60 * 24 * 7, // 7 days
      sameSite: 'Lax', 
      path: '/'
    }
  }
});
